### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by andylmfao** [mineblock11/QuickplayBackport#2]
Doesn't work on curseforge, with the arguments in the launcher it just crashes and says this:
![image](https://github.com/mineblock11/QuickplayBackport/assets/63781863/a6b05aff-89ed-48d0-b9eb-3fc37d86347c)

**Comment by IMB11** [comment]
This is unrelated to Quickplay, put the arguments in launch arguments not JDK arguments.

**Comment by andylmfao** [comment]
Launch arguments are the ones in the launcher, right? Where you also set ram and Targetdirectory? if so, that's what I did. I don't see where else I could put the arguments.

**Comment by IMB11** [comment]
Can you screenshot where you've put the arguments?

**Comment by andylmfao** [comment]
![image](https://github.com/mineblock11/QuickplayBackport/assets/63781863/92e27f88-5e80-43ec-a502-215c8a851794)

In the red square (I have not put any others myself, that is the default CurseForge Arguments)

**Comment by IMB11** [comment]
You need to prepend the argument with `-D` eg: `-DquickplayServer=...` etc.

**Comment by andylmfao** [comment]
`-DquickPlaySingleplayer "New World (1)"` just insta-crashes the game immediately after clicking play.

**Comment by IMB11** [comment]
Please upload your logs - also shouldnt you need an `=` sign between the world name and argument

**Comment by andylmfao** [comment]
Okay so after adding the ´=´ the game opens, but it doesn't launch straight into the world.  

https://mclo.gs/nCfXO4k <-- logs

edit: nvm, still insta-crashes. Idk how i got it to launch, but as you can see in the log the mod doesn't find any arguments. When it crashes, the game doesn't open, so no log is produced. Is there a log for the launcher itself?

**Comment by andylmfao** [comment]
Bump

**Comment by IMB11** [comment]
Thats not a crash log, and the log doesn't instantly crash like you said

**Comment by IMB11** [comment]
also seems to be an error with geckolib, not quickplay, closing as crash unrelated to Quickplay
